// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaYHP5yt943lRiQRQbGIAkGEKuuVHzLUg',
    appId: '1:901533353815:web:d47ca0039d4af79a79a012',
    messagingSenderId: '901533353815',
    projectId: 'scrapit-9b8d4',
    authDomain: 'scrapit-9b8d4.firebaseapp.com',
    storageBucket: 'scrapit-9b8d4.firebasestorage.app',
    measurementId: 'G-FX1GMG4XFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcbGQYrc6MDZzO-uNgDuh2JHTaUCGMl3o',
    appId: '1:901533353815:android:f61ed8a202c1377c79a012',
    messagingSenderId: '901533353815',
    projectId: 'scrapit-9b8d4',
    storageBucket: 'scrapit-9b8d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNS4dfeM_7bw7GjuJK4yOlnqdKp6wfmPo',
    appId: '1:901533353815:ios:3b9ac3c9a386a83879a012',
    messagingSenderId: '901533353815',
    projectId: 'scrapit-9b8d4',
    storageBucket: 'scrapit-9b8d4.firebasestorage.app',
    iosClientId: '901533353815-44li7t4j1vcnhb47lb8mdnc1ninlhkdm.apps.googleusercontent.com',
    iosBundleId: 'com.rhythmgupta.scrapIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNS4dfeM_7bw7GjuJK4yOlnqdKp6wfmPo',
    appId: '1:901533353815:ios:3b9ac3c9a386a83879a012',
    messagingSenderId: '901533353815',
    projectId: 'scrapit-9b8d4',
    storageBucket: 'scrapit-9b8d4.firebasestorage.app',
    iosClientId: '901533353815-44li7t4j1vcnhb47lb8mdnc1ninlhkdm.apps.googleusercontent.com',
    iosBundleId: 'com.rhythmgupta.scrapIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaYHP5yt943lRiQRQbGIAkGEKuuVHzLUg',
    appId: '1:901533353815:web:eebc5a6def2ac3f979a012',
    messagingSenderId: '901533353815',
    projectId: 'scrapit-9b8d4',
    authDomain: 'scrapit-9b8d4.firebaseapp.com',
    storageBucket: 'scrapit-9b8d4.firebasestorage.app',
    measurementId: 'G-9V82LZTN4Q',
  );

}